#ACTIONS
BET = 0#"BET"
CALL = 1#"CALL"
CHECK = 2#"CHECK"
RAISE = 3#"RAISE"
FOLD = 4#"FOLD"
DEAL = 5#"DEAL"
POST = 6#"POST"
REFUND = 7#"REFUND"
SHOW = 8#"SHOW"
TIE = 9#"TIE"
WIN = 10#"WIN"

#STREETS
PREFLOP = 0
FLOP = 1
TURN = 2
RIVER = 4

#PACKET TYPES
NEWGAME = "NEWGAME"
NEWHAND = "NEWHAND"
GETACTION = "GETACTION"
HANDOVER = "HANDOVER"

#ACTION AMOUNT TYPES
POTAMOUNT = "POT AMOUNT"
BETAMOUNT = "BET AMOUNT"
ABSAMOUNT = "ABS AMOUNT"

ACTION_TYPES = ["BET", "CALL", "CHECK", "RAISE", "FOLD", "DEAL", "POST",
                "REFUND", "SHOW", "TIE", "WIN"]
